### ISSUE TITLE
Used proxy server is not updated 

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/vscode-coder#220] opened 2024-02-27 12:04 UTC
https://github.com/coder/vscode-coder/assets/3165839/dd883fea-8dc1-44fa-8233-2ea1fafd546a

In the dashboard, it shows me Brazil as the selected proxy server and even after selecting it again, the VSCode extension is not showing the correct info. I don't know if it is not using the right proxy or if the displayed info is not getting updated.

**Comment by Emyrk** [comment] 2024-02-28 14:47
Proxies can only be chosen for browser based connections. Vscode uses our tailnet connections with auto select. At present, they cannot be manually chosen.

So this is the intended behavior.

The selector on the browser only stores your choice in local storage

**Comment by Emyrk** [comment] 2024-03-05 21:01
I think we can close this issue. This is expected behavior.

**Closed by Emyrk** 2024-03-05 21:01 UTC
Labels: bug
