### ISSUE TITLE
If the selected folder (from recents) doesn't exist, extension says workspace doesn't exist

### ISSUE THREAD

**Issue by mafredri** [coder/vscode-coder#39] opened 2023-01-18 10:27 UTC
This error is a bit confusing, I think it should say folder does not exist (since workspace is up and running):

<img width="302" alt="Screenshot 2023-01-18 at 12 22 22" src="https://user-images.githubusercontent.com/147409/213147673-1c9d44ca-6815-49ee-81e0-49c9a5aed997.png">

**Comment by jsjoeio** [comment] 2023-01-18 15:47
How do you reproduce this? Guessing this simply shows the error message from the API but would have to dig in

**Comment by mafredri** [comment] 2023-01-18 15:55
I think this would reproduce it:

- In workspace: `mkdir ~/deleted`
- In VSCode, open workspace, select File -> Open folder -> ~/deleted
- Close VSCode
- In workspace: `rm ~/deleted`
- Connect via VSCode again, select the `/home/coder/deleted` path (if this is the only recent folder, you won't even be given an option to choose the path)

**Comment by jsjoeio** [comment] 2023-01-18 18:12
Nice! I guess we could look at the error and then check if the folder doesn't exist before assuming the Workspace doesn't exist, right?

**Comment by matifali** [comment] 2024-08-30 14:22
closing because of age. Please reopen or file a new issue if the issue still exists.

**Closed by matifali** 2024-08-30 14:22 UTC
