### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by kylecarbs** [coder/vscode-coder#105] opened 2023-06-09 16:45 UTC
> **Note**
> See [this comment](https://github.com/coder/vscode-coder/issues/105#issuecomment-1645999830) for the latest troubleshooting information and fixes. 

---

VS Code uses a version of Electron that does not support registering self-signed intermediate certificates with extensions on Windows. This unfortunately blocks our ability to perform HTTPS requests securely to a Coder deployment with self-signed certificates.

See https://github.com/electron/electron/issues/38527 for updates an information. We'll fix this as soon as we can!

> **Warning**
> "unable to verify the first certificate" is the error message you'll see. 

![image](https://github.com/coder/vscode-coder/assets/7122116/e9a84083-38f2-4b3a-948a-d2efb7743f83)

**Comment by bpmct** [comment] 2023-06-14 16:47
It seems there are still cases where `allow-insecure: true` does not allow the extension to connect. @kylecarbs is investigating this.

**Comment by code-asher** [comment] 2023-07-06 21:47
How are folks reproducing this?  I tried a self-signed certificate and an untrusted authority but both work on Windows after I add the relevant certificates to the system (I am doing so via `mmc`).  I tested against the following:

- https://untrusted-root.badssl.com
- https://self-signed.badssl.com
- https://localhost:8081 with a Caddy instance proxying to dev.coder.com using a self-signed certificate

All three cases work after I add the certificates (and restart VS Code) so VS Code is indeed reading certificates installed on the system (here by "works" I mean the request goes through without any certificate errors---since the first two are not actual Coder deployments logging in fails with an "invalid token" error).

But those three cases give me variants of "self signed certificate" errors, not the reported error.  This domain can trigger the "unable to verify the first certificate" error though:

- https://incomplete-chain.badssl.com

However this ("incomplete chain") implies to me that the server is misconfigured and nothing can be done on the client to fix this?  

I could not get the  `coder` binary nor Firefox to work against this domain either but the report seem to suggest that people are getting this error while the `coder` binary still works.  If I can figure out how to reproduce that specifically I can continue debugging.

Going to take a look at the Electron bug in the meantime.

**Comment by code-asher** [comment] 2023-07-06 22:07
When I generate my own self-signed certificate it works for the Electron test case.  This leads me to believe that there is a way to generate a certificate that is accepted by Node but not Electron, maybe because Node is missing a check that should cause it to reject the certificate.

Either way, so far this seems to imply that the issue is a certificate that is invalid in some way.  It could be helpful to understand how people are generating the certificates that result in this error so I can reproduce.

**Comment by code-asher** [comment] 2023-07-06 22:16
Another note: I am able to reproduce "unable to get local issuer certificate" in VS Code 1.78.1. This is a bug that was fixed in 1.78.2 but it does not match the reported error so it might be irrelevant anyway.

**Comment by code-asher** [comment] 2023-07-07 17:49
Figured out a way to reproduce:

1. Create a certificate on Windows via Powershell using the New-SelfSignedCertificate command
2. Export the certificate via `mmc`
3. Convert from `.pfx` to `.pem` files using `openssl`

The resulting certificate and key will trigger the Electron error, and if I use them in my Caddy server then Firefox and the coder binary both accept the certificate but in VS Code I get the "unable to verify the first certificate" error, as expected since Electron gives the same error.

So we come back to needing to figure out why Electron's behavior is different.

**Comment by sreya** [comment] 2023-07-11 17:22
Un-assigning @code-asher in favor of https://github.com/coder/vscode-coder/issues/115 since that is specifically tracking the investigation of the root cause of the bug since it's a little uncertain where in the upstream dependency chain things are breaking.

**Comment by bpmct** [comment] 2023-07-21 17:03
@code-asher gave me a great run-down of what is going on here (and helped with edits to this summary). There are 2 issues that users are running into that we are aware of.

## Case 1) Partial certificate chain on server

You are likely running into this if Coder warns you the certificate is self-signed, and when you press "allow insecure," you get stuck in an infinite refresh loop and Coder doesn't let you connect.

- `golang`, `curl`, and Google Chrome all accept a "leaf" certificate if it is trusted on the client machine (so they do not require any intermediates or roots)
- `node` requires a leaf + intermediate certificate server certs which must be signed by a root certificate trusted by the system

**The fix for Coder admins**: Update the certificates on the server to include both the leaf certificate + intermediate cert. You can `cat` them together into one file, starting at the leaf and going up the chain (so leaf first, then next intermediate, and so on)

**To improve the UX**: The Coder extension should attempt to detect (by parsing the server certificate) whether it is a partial chain. If so, we should hide the "allow insecure" button (since it does not help in this case). Instead, we link to docs on a GitHub issue on how to change the server certificate to work with `node`. 
> If it's not easy to detect if the problem is case 1 or case 2, we should link to both issues in the "insecure" popup that the extension creates.

## Case 2) A certificate does not have signing capabilities

You are likely running into this if Coder warns you the certificate is self-signed, and when you press "allow insecure," you are able to connect to the workspace 🎉 

- `openssl` accept these certificates anyways
- `boringssl`, the SSL library that `node`, uses does not accept certificates if the system certificate does not have signing capabilities. 

More details + the fix for Coder users and admins are outlined here: https://github.com/coder/vscode-coder/issues/115#issuecomment-1631512493

**To improve the UX**: We are working on a patch upstream to `boringssl`, but this will take some time. In the meantime, the "allow insecure" button should work in the pop-up dialog or you can follow the docs above to regenerate your local certificates with signing capabilities.

**Comment by pjmckee** [comment] 2023-10-08 02:23
Hey @kylecarbs @bpmct just checking to see if any permanent solution has been found for this issue? We are evaluating coder for our platform, eventually enterprise, and ran into this issue when launching vscode from coder. I saw @code-asher's reply [#115](https://github.com/coder/vscode-coder/issues/115#issuecomment-1631512493) but unfortunately we work in a restricted environment and our CA will not allow the coder server's certificate to have keyUsage: Certificate Sign, so we are without a way around it. We have loaded our entire bundle onto the coder server and tried allow insecure but no luck.

**Comment by code-asher** [comment] 2023-10-11 22:58
Has the root certificate also been added to the client machine's trust store?  Unfortunately the `allow insecure` option is bugged, for some reason it just does nothing in VS Code so that is something we need to investigate, but for now it means the certificates need to be trusted on the client.

**Comment by pjmckee** [comment] 2023-10-12 22:40
hey @code-asher thanks for the follow-up. Yes the root and intermediates are installed on the client's trust store. Tried adding those to the coder image as a test as well, but am still met with the error saying "Your certificate is not capable of signing...".

**Comment by code-asher** [comment] 2023-10-13 20:57
Ah OK bummer.  That does seem weird though.  That error happens when we get `unable to verify leaf signature`, and that error happens when the leaf certificate is the only one available (if I am reading [the code](https://github.com/google/boringssl/blob/master/crypto/x509/x509_vfy.c#L1709-L1718) right).  

Does it look like the certificates are properly chained?  Like the leaf certificate has an issuer and key id fields pointing to the next certificate, etc.  For example (some parts omitted for brevity):

```
coder@dev27:~/vscode-coder/fixtures$ openssl x509 -text -noout -in chain-leaf.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4096 (0x1000)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = TEST-intermediate
        Validity
            Not Before: Oct 13 20:35:09 2023 GMT
            Not After : Sep 19 20:35:09 2123 GMT
        Subject: CN = localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
        X509v3 extensions:
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Alternative Name: 
                DNS:localhost
            X509v3 Subject Key Identifier: 
                5A:7A:13:6C:1C:53:64:9E:A9:D8:C5:D3:BF:8A:3C:29:94:59:1E:90
            X509v3 Authority Key Identifier: 
                12:32:21:AD:6E:A1:48:3E:36:77:DB:DF:78:DB:53:D4:4C:FA:79:A7
```

If we can figure out how to generate a chain similar to the ones used in your setup I can attempt to reproduce.

**Comment by Kira-Pilot** [comment] 2024-05-15 18:45
Closing this out as we'd have to push a fix to `boringssl` and this has limited scope. We can re-open if we hear more feedback on this in the future.

**Closed by Kira-Pilot** 2024-05-15 18:45 UTC

**Comment by vaskokj** [comment] 2025-05-22 03:17
@bpmct 

Could you maybe explain in more detail (which config setting) is being referenced here.

> The fix for Coder admins: Update the certificates on the server to include both the leaf certificate + intermediate cert. You can cat them together into one file, starting at the leaf and going up the chain (so leaf first, then next intermediate, and so on)

Specifically which certificates? The CA bundle? The servers TLS certs? If this in reference to the CA cert bundle?  This setting? https://github.com/coder/coder/blob/53e8e9c7cd5a24d42e5c51e6b6335ad8be692db9/helm/coder/values.yaml#L210 If so i have my full CA bundle set there, and still seem to be getting this error which I believe puts me in case 1):



> PARTIAL_CHAIN = "Your Coder deployment's certificate cannot be verified because a certificate is missing from its chain. To fix this your deployment's administrator should bundle the missing certificates or you can add the missing certificates directly to this system's trust store."

https://github.com/coder/vscode-coder/issues/105#issuecomment-1645999830

**Comment by code-asher** [comment] 2025-05-22 18:30
> Specifically which certificates? The CA bundle? The servers TLS certs? If this in reference to the CA cert bundle?

The "fix for Coder admins" line is in reference to the server's TLS certificates.  So, if my deployment was coder.com, it would be in reference to the certificate(s) you would get if you were to run `openssl s_client -showcerts -connect coder.com:443` for example.

Once the site is serving the full chain you then need to make sure the root certificate is trusted in both the workspace and your local machine, if you are using an internal CA or something.

**Comment by vaskokj** [comment] 2025-05-23 13:34
@code-asher 

Thanks! This got me fixed

I had already included my full chained CA bundle for Coder with this config setting https://github.com/coder/coder/blob/53e8e9c7cd5a24d42e5c51e6b6335ad8be692db9/helm/coder/values.yaml#L210 which is what I thought it was asking for but obviously wasn't. 


Our k8s cluster is set up where our ingress controller has a wild card cert, which _only_ had the "leaf". I am calling it a "leaf" as that is the dns name the cert is created for. So we had something like the following in the crt file and that was it. 

`leaf - *.k8s.example.com`

The fix (which I didn't realize was something you could even do...) was to make the crt file.

```
leaf - *.k8s.example.com
intermediate CA crt
root CA crt 
```

I put this file on our ingress controller and Coder started working. 

One thing I am confused about is the difference between

https://github.com/coder/coder/blob/53e8e9c7cd5a24d42e5c51e6b6335ad8be692db9/helm/coder/values.yaml#L319

and 

https://github.com/coder/coder/blob/53e8e9c7cd5a24d42e5c51e6b6335ad8be692db9/helm/coder/values.yaml#L156

So in my case I’m using my k8s clusters ingress controller itself to provide the TLS termination via wild cards URLs. If I wasn’t doing that my solution would be to provide my full root chain cert to line 319 (which I didn't test but I assume would accomplish the same thing), but i’m unclear on what line 156 is doing.
